name: build

on:
  push:
    paths:
      - common/**
      - src_gui/**
      - src_nogui/**
      - updater/**
      - resource/**
      - CMakeLists.txt
      - utilities.cmake
      - .github/workflows/build.yml
  workflow_dispatch:

jobs:
  build-nogui:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with: { arch: x64 }
      - run: vcpkg install yalantinglibs:x64-windows
      - run: cmake -B build_nogui -DBUILD_GUI=OFF -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
      - run: cmake --build build_nogui --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: dwrgFpsUnlocker_nogui
          path: build_nogui/src_nogui/Release/dwrgFpsUnlocker_nogui.exe

  build-gui:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt 6.8.0 via aqtinstall
        run: |
          pip install aqtinstall
          aqt install-qt windows desktop 6.8.2 win64_msvc2022_64 -O C:/Qt

      - uses: ilammy/msvc-dev-cmd@v1
        with: { arch: x64 }

      - name: Install deps via vcpkg
        run: vcpkg install yalantinglibs:x64-windows --head

      - name: Build QHotKey (Qt6)
        run: |
          git clone --depth 1 https://github.com/Skycoder42/QHotkey.git C:/qhotkey
          cmake -B C:/qhotkey/build -S C:/qhotkey -DCMAKE_PREFIX_PATH=C:/Qt/6.8.2/msvc2022_64 -DQT_DEFAULT_MAJOR_VERSION=6
          cmake --build C:/qhotkey/build --config Release
          cmake --install C:/qhotkey/build --prefix C:/qhotkey/install

      - name: Configure CMake (gui)
        run: cmake -B build_gui -DBUILD_GUI=ON -DBUILD_SINGLE=ON -DCMAKE_PREFIX_PATH="C:/Qt/6.8.2/msvc2022_64;C:/qhotkey/install" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCI_BUILD=ON

      - name: Build
        run: cmake --build build_gui --config Release

      - uses: actions/upload-artifact@v4
        with:
          name: dwrgFpsUnlocker_gui
          path: build_gui/src_gui/Release/dwrgFpsUnlocker.exe